// AUTO-GENERATED by tools/gen_sprites.py — sprite asset lookups.
#pragma once
#include <stdint.h>
struct PixelArt { uint8_t w, h; const uint16_t* px; };
constexpr uint16_t ART_TRANSPARENT = 0xF81F;
const PixelArt* artForItem(uint16_t itemId);   // character item ids (0-11, 60-71), else nullptr
const PixelArt* artForDino(uint8_t idx);       // 0-11
const PixelArt* artForShark(uint8_t idx);      // 0-5
const PixelArt* artGoalie();
