// AUTO-GENERATED by tools/gen_sprites.py — do not edit by hand.
#include "Assets.h"
#include "AssetsData.h"

namespace {
const PixelArt kArt_default_princess = {48, 48, ART_DEFAULT_PRINCESS};
const PixelArt kArt_ella = {48, 48, ART_ELLA};
const PixelArt kArt_ari = {48, 48, ART_ARI};
const PixelArt kArt_raphy = {48, 48, ART_RAPHY};
const PixelArt kArt_cindy = {48, 48, ART_CINDY};
const PixelArt kArt_mona = {48, 48, ART_MONA};
const PixelArt kArt_rebecca = {48, 48, ART_REBECCA};
const PixelArt kArt_mermaid = {48, 48, ART_MERMAID};
const PixelArt kArt_fairy = {48, 48, ART_FAIRY};
const PixelArt kArt_unicorn = {48, 48, ART_UNICORN};
const PixelArt kArt_bunny = {48, 48, ART_BUNNY};
const PixelArt kArt_kitten = {48, 48, ART_KITTEN};
const PixelArt kArt_soccer_player = {48, 48, ART_SOCCER_PLAYER};
const PixelArt kArt_dino_trainer = {48, 48, ART_DINO_TRAINER};
const PixelArt kArt_trex_character = {48, 48, ART_TREX_CHARACTER};
const PixelArt kArt_raptor_character = {48, 48, ART_RAPTOR_CHARACTER};
const PixelArt kArt_shark_character = {48, 48, ART_SHARK_CHARACTER};
const PixelArt kArt_spidey = {48, 48, ART_SPIDEY};
const PixelArt kArt_cowboy = {48, 48, ART_COWBOY};
const PixelArt kArt_astro = {48, 48, ART_ASTRO};
const PixelArt kArt_astronaut = {48, 48, ART_ASTRONAUT};
const PixelArt kArt_robot = {48, 48, ART_ROBOT};
const PixelArt kArt_explorer = {48, 48, ART_EXPLORER};
const PixelArt kArt_frankie = {48, 48, ART_FRANKIE};
const PixelArt kArt_dino_00 = {48, 48, ART_DINO_00};
const PixelArt kArt_dino_01 = {48, 48, ART_DINO_01};
const PixelArt kArt_dino_02 = {48, 48, ART_DINO_02};
const PixelArt kArt_dino_03 = {48, 48, ART_DINO_03};
const PixelArt kArt_dino_04 = {48, 48, ART_DINO_04};
const PixelArt kArt_dino_05 = {48, 48, ART_DINO_05};
const PixelArt kArt_dino_06 = {48, 48, ART_DINO_06};
const PixelArt kArt_dino_07 = {48, 48, ART_DINO_07};
const PixelArt kArt_dino_08 = {48, 48, ART_DINO_08};
const PixelArt kArt_dino_09 = {48, 48, ART_DINO_09};
const PixelArt kArt_dino_10 = {48, 48, ART_DINO_10};
const PixelArt kArt_dino_11 = {48, 48, ART_DINO_11};
const PixelArt kArt_shark_00 = {48, 48, ART_SHARK_00};
const PixelArt kArt_shark_01 = {48, 48, ART_SHARK_01};
const PixelArt kArt_shark_02 = {48, 48, ART_SHARK_02};
const PixelArt kArt_shark_03 = {48, 48, ART_SHARK_03};
const PixelArt kArt_shark_04 = {48, 48, ART_SHARK_04};
const PixelArt kArt_shark_05 = {48, 48, ART_SHARK_05};
const PixelArt kArt_goalie = {48, 48, ART_GOALIE};

const PixelArt* const kDinos[12] = {
  &kArt_dino_00, &kArt_dino_01, &kArt_dino_02, &kArt_dino_03, &kArt_dino_04, &kArt_dino_05,
  &kArt_dino_06, &kArt_dino_07, &kArt_dino_08, &kArt_dino_09, &kArt_dino_10, &kArt_dino_11,
};
const PixelArt* const kSharks[6] = {
  &kArt_shark_00, &kArt_shark_01, &kArt_shark_02, &kArt_shark_03, &kArt_shark_04, &kArt_shark_05,
};
}  // namespace

const PixelArt* artForItem(uint16_t itemId) {
  switch (itemId) {
    case 0: return &kArt_default_princess;
    case 1: return &kArt_ella;
    case 2: return &kArt_ari;
    case 3: return &kArt_raphy;
    case 4: return &kArt_cindy;
    case 5: return &kArt_mona;
    case 6: return &kArt_rebecca;
    case 7: return &kArt_mermaid;
    case 8: return &kArt_fairy;
    case 9: return &kArt_unicorn;
    case 10: return &kArt_bunny;
    case 11: return &kArt_kitten;
    case 60: return &kArt_soccer_player;
    case 61: return &kArt_dino_trainer;
    case 62: return &kArt_trex_character;
    case 63: return &kArt_raptor_character;
    case 64: return &kArt_shark_character;
    case 65: return &kArt_spidey;
    case 66: return &kArt_cowboy;
    case 67: return &kArt_astro;
    case 68: return &kArt_astronaut;
    case 69: return &kArt_robot;
    case 70: return &kArt_explorer;
    case 71: return &kArt_frankie;
    default: return nullptr;
  }
}

const PixelArt* artForDino(uint8_t idx) {
  return idx < 12 ? kDinos[idx] : nullptr;
}

const PixelArt* artForShark(uint8_t idx) {
  return idx < 6 ? kSharks[idx] : nullptr;
}

const PixelArt* artGoalie() { return &kArt_goalie; }

// ---- ROUND 2: kid player tiles (appended by gen_sprites.py kids-emit) ----
namespace {
const PixelArt kArt_hugo_kid = {48, 48, ART_HUGO_KID};
const PixelArt kArt_stella_kid = {48, 48, ART_STELLA_KID};
}  // namespace

const PixelArt* artKid(uint8_t playerId) {
  if (playerId == 0) return &kArt_hugo_kid;
  if (playerId == 1) return &kArt_stella_kid;
  return nullptr;
}
