// AUTO-GENERATED by tools/gen_sprites.py icons-emit — do not edit by hand.
#include "Icons.h"
#include "IconsData.h"

namespace {
const PixelArt kIcon_apple = {24, 24, ICON_APPLE};
const PixelArt kIcon_smiley = {24, 24, ICON_SMILEY};
const PixelArt kIcon_moon = {24, 24, ICON_MOON};
const PixelArt kIcon_coin = {24, 24, ICON_COIN};
const PixelArt kIcon_tick = {24, 24, ICON_TICK};
const PixelArt kIcon_cross = {24, 24, ICON_CROSS};
const PixelArt kIcon_star = {24, 24, ICON_STAR};
const PixelArt kIcon_heart = {24, 24, ICON_HEART};
const PixelArt kIcon_ball = {24, 24, ICON_BALL};
const PixelArt kIcon_dino = {24, 24, ICON_DINO};
const PixelArt kIcon_shark = {24, 24, ICON_SHARK};
const PixelArt kIcon_crown = {24, 24, ICON_CROWN};
const PixelArt kIcon_butterfly = {24, 24, ICON_BUTTERFLY};
const PixelArt kIcon_wand = {24, 24, ICON_WAND};
const PixelArt kIcon_note = {24, 24, ICON_NOTE};
const PixelArt kIcon_paw = {24, 24, ICON_PAW};
const PixelArt kIcon_bone = {24, 24, ICON_BONE};
const PixelArt kIcon_timer = {24, 24, ICON_TIMER};
const PixelArt kIcon_shirt = {24, 24, ICON_SHIRT};
const PixelArt kIcon_book = {24, 24, ICON_BOOK};
const PixelArt kIcon_bed = {24, 24, ICON_BED};
const PixelArt kIcon_broom = {24, 24, ICON_BROOM};
const PixelArt kIcon_shoe = {24, 24, ICON_SHOE};
const PixelArt kIcon_plate = {24, 24, ICON_PLATE};
const PixelArt kIcon_water = {24, 24, ICON_WATER};
const PixelArt kIcon_gift = {24, 24, ICON_GIFT};
const PixelArt kIcon_home = {24, 24, ICON_HOME};
const PixelArt kIcon_games = {24, 24, ICON_GAMES};
const PixelArt kIcon_shop = {24, 24, ICON_SHOP};
const PixelArt kIcon_missions = {24, 24, ICON_MISSIONS};
const PixelArt kIcon_collection = {24, 24, ICON_COLLECTION};
const PixelArt kIcon_settings = {24, 24, ICON_SETTINGS};
const PixelArt kIcon_swap = {24, 24, ICON_SWAP};
const PixelArt kIcon_jellybean = {24, 24, ICON_JELLYBEAN};
const PixelArt kIcon_sparkle = {24, 24, ICON_SPARKLE};
}  // namespace

const PixelArt* iconArt(uint8_t iconId) {
  switch (iconId) {
    case 1: return &kIcon_apple;  // IconId::Apple
    case 2: return &kIcon_smiley;  // IconId::Smiley
    case 3: return &kIcon_moon;  // IconId::Moon
    case 4: return &kIcon_coin;  // IconId::Coin
    case 5: return &kIcon_tick;  // IconId::Tick
    case 6: return &kIcon_cross;  // IconId::Cross
    case 7: return &kIcon_star;  // IconId::Star
    case 8: return &kIcon_heart;  // IconId::Heart
    case 9: return &kIcon_ball;  // IconId::Ball
    case 10: return &kIcon_dino;  // IconId::Dino
    case 11: return &kIcon_shark;  // IconId::Shark
    case 12: return &kIcon_crown;  // IconId::Crown
    case 13: return &kIcon_butterfly;  // IconId::Butterfly
    case 14: return &kIcon_wand;  // IconId::Wand
    case 15: return &kIcon_note;  // IconId::Note
    case 16: return &kIcon_paw;  // IconId::Paw
    case 17: return &kIcon_bone;  // IconId::Bone
    case 18: return &kIcon_timer;  // IconId::Timer
    case 19: return &kIcon_shirt;  // IconId::Shirt
    case 20: return &kIcon_book;  // IconId::Book
    case 21: return &kIcon_bed;  // IconId::Bed
    case 22: return &kIcon_broom;  // IconId::Broom
    case 23: return &kIcon_shoe;  // IconId::Shoe
    case 24: return &kIcon_plate;  // IconId::Plate
    case 25: return &kIcon_water;  // IconId::Water
    case 26: return &kIcon_gift;  // IconId::Gift
    case 27: return &kIcon_home;  // IconId::Home
    case 28: return &kIcon_games;  // IconId::Games
    case 29: return &kIcon_shop;  // IconId::Shop
    case 30: return &kIcon_missions;  // IconId::Missions
    case 31: return &kIcon_collection;  // IconId::Collection
    case 32: return &kIcon_settings;  // IconId::Settings
    case 33: return &kIcon_swap;  // IconId::Swap
    case 37: return &kIcon_jellybean;  // IconId::JellyBean
    case 38: return &kIcon_sparkle;  // IconId::Sparkle
    default: return nullptr;
  }
}
