// AUTO-GENERATED by tools/gen_sprites.py icons-emit — pixel icon lookups.
#pragma once
#include <stdint.h>
#include "Assets.h"  // PixelArt + ART_TRANSPARENT

// 24x24 pixel art for an IconId numeric value (enum order in UI.h), or
// nullptr for icons that stay procedural (None, Back, arrows, Sun..Web).
const PixelArt* iconArt(uint8_t iconId);
